export const brandsAndModels = {
  // Point1
  'Dacia': [{ name: 'Duster', type: 'SUV' },
            { name: 'Sandero', type: 'Citadine' },
            { name: 'Logan', type: 'Berline' },
            { name: 'Lodgy', type: 'Monospace' },
            { name: 'Jogger', type: 'Monospace' },
            { name: 'Sandero Stepway', type: 'SUV' }],
  'Suzuki': [{name: 'Swift', type: 'Citadine'},
            {name: 'Vitara', type: 'SUV'},
            {name: 'Baleno', type: 'Compacte'},
            {name: 'Maruti', type: 'Citadine'},
            {name: 'Celerio', type: 'Citadine'},
            {name: 'Alto', type: 'Citadine'},],
  'Citroen': [{name: 'C3', type: 'Citadine'},
              {name: 'C4', type: 'Compacte'},
              {name: 'C5 Aircross', type: 'SUV'},
              {name: 'Berlingo', type: 'Monospace'},
              {name: 'C Elysee', type: 'Berline'}],
  'Geely': [{name: 'Coolray', type: 'SUV'}],
  'Chery': [{name: 'Tiggo 2 Pro', type: 'SUV'},
            {name: 'Tiggo 4 Pro', type: 'SUV'},
            {name: 'QQ', type: 'Citadine'},],
  'Chevrolet': [{name: 'Aveo', type: 'Compacte'},
                {name: 'Sail', type: 'Compacte'},
                {name: 'Captiva', type: 'SUV'},
                {name: 'Optra', type: 'Compacte'},
                {name: 'Spark', type: 'Citadine'}],
  // Point2
  'Hyundai': [{
    name: 'i10', type: 'Citadine'
  }, {
    name: 'i20', type: 'Citadine'
  }, {
    name: 'i30', type: 'Compacte'
  }, {
    name: 'Tucson', type: 'SUV'
  }, {
    name: 'Creta', type: 'SUV'
  }, {
    name: 'Santa Fe', type: 'SUV'
  }, {
    name: 'Accent', type: 'Compacte'
  }, {
    name: 'Elantra', type: 'Berline'
  }],
  'Renault': [ { name: 'Clio', type: 'Citadine'},
               { name: 'Megane', type: 'Compacte'},
               { name: 'Kangoo', type: 'Utilitaire'},
               { name: 'Twingo', type: 'Citadine'},
               { name: 'Arkana', type: 'SUV'},
               { name: 'Captur', type: 'SUV'},
               { name: 'Kadjar', type: 'SUV'},
               { name: 'Scenic', type: 'Monospace'},
            { name: 'Symbol', type: 'Berline'},],
  'Skoda': [{name: 'Fabia', type: 'Citadine'},
            {name: 'Octavia', type: 'Berline'},
            {name: 'Rapid', type: 'Berline'},
            {name: 'Kodiaq', type: 'SUV'},
            {name: 'Karoq', type: 'SUV'},
            {name: 'Superb', type: 'Berline'},
            {name: 'Kamiq', type: 'SUV'},
            {name: 'Scala', type: 'Compacte'},],
  'Ford': [{ name: 'Fiesta', type: 'Citadine' },
           { name: 'Focus', type: 'Compacte' },
           { name: 'Puma', type: 'SUV' },
           { name: 'Ranger', type: 'Pickup' },
           { name: 'Kuga', type: 'SUV' }],
  'Seat': [{name: 'Ibiza', type: 'Citadine'},
           {name: 'Leon', type: 'Compacte'},
           {name: 'Arona', type: 'SUV'},
           {name: 'Ateca', type: 'SUV'}],
  'Nissan': [{name: 'Micra', type: 'Citadine'},
             {name: 'Juke', type: 'SUV'},
             {name: 'Qashqai', type: 'SUV'},
             {name: 'Navara', type: 'Pickup'},
             {name: 'Sunny', type: 'Berline'},
             {name: 'Patrol', type: 'SUV'}],
  'Fiat': [{name: '500', type: 'Citadine'},
              {name: 'Tipo', type: ['Compacte', 'Berline']},
              {name: '500X', type: 'SUV'},
              {name: 'Doblo', type: 'Utilitaire'},],
  'Opel': [{name: 'Corsa', type: 'Citadine'},
           {name: 'Astra', type: 'Compacte'},
           {name: 'Mokka', type: 'SUV'},
           {name: 'Grandland', type: 'SUV'},
           {name: 'Insignia', type: 'Berline'}],
  'Jetour': [{name: 'Dashing', type: 'SUV'},
             {name: 'X70 Plus', type: 'SUV'},
             {name: 'X90', type: 'SUV'},
             {name: 'X70', type: 'SUV'},],
  'Mitsubishi': [{name: 'Outlander', type: 'SUV'},
                 {name: 'L200', type: 'Pickup'},],
  // Point3
  'Volkswagen': [{ name: 'Golf', type: 'Compacte' },
                 { name: 'Polo', type: 'Citadine' },
                 { name: 'Tiguan', type: 'SUV' },
                 { name: 'Passat', type: 'Berline' },
                 { name: 'Touareg', type: 'SUV' },
                 { name: 'Touran', type: 'Monospace' },
                 { name: 'Caddy', type: 'Utilitaire' },
                 { name: 'T-Roc', type: 'SUV' },
                 { name: 'Arteon', type: 'Berline' },
                 { name: 'T-Cross', type: 'SUV' },
                { name: 'Taigo', type: 'SUV' }],
  'Peugeot': [{ name: '208', type: 'Citadine' },
              { name: '308', type: 'Compacte' },
              { name: '3008', type: 'SUV' },
              { name: '2008', type: 'SUV' },
              { name: '508', type: 'Berline' },
              { name: 'Rifter', type: 'Utilitaire' },
              { name: 'Partner', type: 'Utilitaire' },
              { name: '5008', type: 'SUV' },
              { name: '307', type: 'Compacte' },
              { name: '207', type: 'Citadine' },
              { name: '206', type: 'Citadine' },],
  'Kia': [{ name: 'Rio', type: 'Citadine' },
          { name: 'Ceed', type: 'Compacte' },
          { name: 'Sportage', type: 'SUV' },
          { name: 'Picanto', type: 'Citadine' },
          { name: 'Seltos', type: 'SUV' },
          { name: 'Stonic', type: 'SUV' },
          { name: 'Sorento', type: 'SUV' },
          { name: 'Carens', type: 'Monospace' }],
  'Toyota': [{ name: 'Yaris', type: 'Citadine' },
             { name: 'Corolla', type: ['Compacte', 'Berline'] },
             { name: 'RAV4', type: 'SUV' },
             { name: 'C-HR', type: 'SUV' },
             { name: 'Hilux', type: 'Pickup' },
             { name: 'Land Cruiser', type: 'SUV' },
             { name: 'Aygo', type: 'Citadine' }],
  'Cupra': [{name: 'Formentor', type: 'SUV'},],
  'DS': [{name: 'DS7', type: 'SUV'},
         {name: 'DS5', type: 'Compacte'},
         {name: 'DS3', type: 'Citadine'},
         {name: 'DS4', type: 'Compacte'}],
  // Point4
  'Audi': [{name: 'A1', type: 'Citadine'},
           {name: 'A3', type: 'Compacte'},
           {name: 'A4', type: 'Berline'},
           {name: 'A6', type: 'Berline'},
           {name: 'Q2', type: 'SUV'},
           {name: 'Q3', type: 'SUV'},
           {name: 'Q5', type: 'SUV'},
           {name: 'Q7', type: 'SUV'},],
  'Mercedes': [{name: 'Class A', type: 'Compacte'},
                {name: 'ML', type: 'SUV'},
                {name: 'Class C', type: 'Berline'},
                {name: 'Class E', type: 'Berline'},
                {name: 'Class GLA', type: 'SUV'},
                {name: 'Class GLC', type: 'SUV'},
                {name: 'Class GLE', type: 'SUV'},],
  'BMW': [{ name: 'Serie 1', type: 'Compacte' },
          { name: 'Serie 3', type: 'Berline' },
          { name: 'Serie 5', type: 'Berline' },
          { name: 'X1', type: 'SUV' },
          { name: 'X3', type: 'SUV' },
          { name: 'X5', type: 'SUV' },
          { name: 'X4', type: 'SUV' },
          { name: 'X6', type: 'SUV' },],
  'Land Rover': [{ name: 'Evoque', type: 'SUV' },
                    { name: 'Discovery', type: 'SUV' },
                    { name: 'Range Rover', type: 'SUV' }],
  // Point5
  'Porsche': [{name: 'Macan', type: 'SUV'},
              {name: 'Cayenne', type: 'SUV'}]
};

export const carTypes = ['Citadine', 'Compacte', 'Berline', 'SUV', 'Pickup', 'Utilitaire'];
export const colors = ['Noir', 'Blanc', 'Gris', 'Bleu', 'Rouge', 'Vert', 'Marron', 'Jaune', 'Orange', 'Argent']; // Gardé en autocomplétion
export const fuelTypes = ['Essence', 'Diesel', 'GPL', 'Hybride'];
export const gearboxTypes = ['Manuelle', 'Automatique'];
export const papersOptions = [
    { value: 'ok', label: 'Carte Grise Propre' },
    { value: 'no', label: 'Licence / Délai' }
];